export const CATEGORIES = [
  { id: 'Cellphone', label: 'Cellphone', icon: 'fa-solid fa-mobile-screen-button', emoji: '📱' },
  { id: 'Laptop', label: 'Laptop', icon: 'fa-solid fa-laptop', emoji: '💻' },
  { id: 'Tablet', label: 'Tablet', icon: 'fa-solid fa-tablet-screen-button', emoji: '📟' },
  { id: 'ID Card', label: 'ID Card', icon: 'fa-solid fa-address-card', emoji: '🪪' },
  { id: 'Wallet', label: 'Wallet', icon: 'fa-solid fa-wallet', emoji: '👛' },
  { id: 'Bag / Backpack', label: 'Bag / Backpack', icon: 'fa-solid fa-bag-shopping', emoji: '🎒' },
  { id: 'Keys', label: 'Keys', icon: 'fa-solid fa-key', emoji: '🔑' },
  { id: 'Headphones / Earbuds', label: 'Headphones / Earbuds', icon: 'fa-solid fa-headphones', emoji: '🎧' },
  { id: 'Watch / Wearable', label: 'Watch / Wearable', icon: 'fa-solid fa-clock', emoji: '⌚' },
  { id: 'Water Bottle', label: 'Water Bottle', icon: 'fa-solid fa-bottle-water', emoji: '🥤' },
  { id: 'Umbrella', label: 'Umbrella', icon: 'fa-solid fa-umbrella', emoji: '🌂' },
  { id: 'Eyewear', label: 'Eyewear', icon: 'fa-solid fa-glasses', emoji: '🕶️' },
  { id: 'Book', label: 'Book', icon: 'fa-solid fa-book', emoji: '📖' },
  { id: 'Notebook', label: 'Notebook', icon: 'fa-solid fa-book-open', emoji: '📓' },
  { id: 'Stationery', label: 'Stationery', icon: 'fa-solid fa-pen-nib', emoji: '✏️' },
  { id: 'Clothing', label: 'Clothing', icon: 'fa-solid fa-shirt', emoji: '👕' },
  { id: 'Accessories', label: 'Accessories', icon: 'fa-solid fa-gem', emoji: '💍' },
  { id: 'Other', label: 'Other', icon: 'fa-solid fa-box-archive', emoji: '📦' },
];
